
---
- name: Install & Configure MSSQL
  hosts: database:&{{scope}}
  gather_facts: yes
  become: yes

  vars:
    rhn_username: "{{ rhsm_username }}"
    rhn_password: "{{ rhsm_password }}"
    rh_poolid: "{{ rhpoolid }}"

  tasks:

    - name: Including EAP role 
      include_role:
        name: eap
      vars:
        eap_tags_for_database: "database:&{{scope}}"
        eap_tags_for_eap: "eap:&{{scope}}"
        db_name: monolith
        db_creation_date: "{{ ansible_date_time.date }}"
        db_project: "project_{{scope}}"
        db_user: sa
