---
- name: Create Azure Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Including azure role for lab creation
      include_role:
        name: azure
        tasks_from: azure_env_setup

    - name: Create Database VM
      include_role:
        name: azure
      vars:
        az_application: 'database'
        az_purpose: "{{ scope }}"
        az_count: 1
        az_scope: 'database'

    - name: Create EAP VM
      include_role:
        name: azure
      vars:
        az_application: 'eap'
        az_purpose: "{{ scope }}"
        az_count: 1
        az_scope: 'eap'



