---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Including ec2 role for lab creation
      include_role:
        name: ec2
        tasks_from: ec2_env_setup

    - name: Create Database VM
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}"
          Role: database
        ec2_count: 1
        ec2_size: t2.medium
        ec2_ami: ami-02ace471
        # ec2_groupid: sg-03580ee6c98db6051
        ec2_lb_filters: 
          'tag:Name': "{{ ec2_scope }}"
          'tag:Role': database
          'instance-state-name': running
  
    - name: Create EAP VMs
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}"
          Role: eap
        ec2_size: t2.medium
        ec2_count: "{{ eap_ec2_count }}"
        ec2_ami: ami-0e12cbde3e77cbb98
        # ec2_groupid: sg-06bf8abd04830d9ff
        ec2_lb_filters: 
          'tag:Name': "{{ ec2_scope }}"
          'tag:Role': eap
          'instance-state-name': running


#    - name: Refresh inventory 
#      meta: refresh_inventory

