---
- name: Create Azure Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Select VM size
      set_fact:
        az_actual_size: "{{ tee_shirt_sizes[infra_size] }}"
      vars:
        tee_shirt_sizes: 
          dev: Standard_B2ms
          prod: Standard_B4ms
          perf: Standard_B8ms

    - name: Including azure role for ressource group creation
      include_role:
        name: azure
        tasks_from: azure_env_setup

    - name: Create Database VM
      include_role:
        name: azure
      vars:
        az_application: 'database'
        az_purpose: "{{ scope }}"
        az_size: "{{ az_actual_size }}"
        az_count: 1
        az_scope: 'database'
        az_loadbalanced: no

    - name: Create EAP VM
      include_role:
        name: azure
      vars:
        az_application: 'eap'
        az_purpose: "{{ scope }}"
        az_size: "{{ az_actual_size }}"
        az_count: 1
        az_scope: 'eap'
        az_loadbalanced: yes



