---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Including ec2 role for infrastructure creation
      include_role:
        name: azure
        tasks_from: azure_env_setup.yml
