- name: Manage Azure loadbalancer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
         
    - name: Include tasks for load balancer control
      include_role:
        name: azure
        tasks_from: azure_loadbalancer.yml
    