- name: rhsm_unregister
  redhat_subscription:
    state: absent
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
  ignore_errors: yes

- name: insights_unregister
  command: redhat-access-insights --unregister
  ignore_errors: yes

- name: restart_nginx
  service:
    name: nginx
    state: restarted
    
